---
- name: "Security / Firewall / OS / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sec_firewall_os_platforms

- name: "Security / Firewall / OS / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + sec_firewall_os_family + '.yml' }}"
  changed_when: false

- name: "Security / Firewall / OS / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sec_firewall_os_prerequisite.yml"
  when:
    - "'resolve_prereq' in sec_firewall_os"
    - sec_firewall_os['resolve_prereq']
...
