---
sys_sudo_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

sys_sudo_profiles:
  distro:
    latest:
      packages:
        - name: "sudo"

sys_sudo_base:
  etc:
    sudoers: "/etc/sudoers"
  run:
    visudo: "/usr/sbin/visudo"
...
