---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_package:
          provision: true
        sys_package_application: "{{ test_sys_package_application_pip }}"
        sys_package_profiles:
          pip:
            latest:
              packages:
                - name: "mkdocs"
              options:
                pip:
                  owner: "{{ test_user }}"
                  group: "{{ test_group }}"
                  path: "{{ test_pip_path }}"
                  cli: "mkdocs"
      ansible.builtin.include_role:
        name: "sys_package"
...
