---
bkp_restic_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

bkp_restic_base:
  access:
    owner: "root"
    group: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  paths:
    root: "/opt/restic"
    bin: "/opt/restic/bin"
    etc: "/opt/restic/etc"
  run:
    restic: "/opt/restic/bin/restic"

bkp_restic_profiles:
  binary:
    v0_12:
      origin: "https://github.com/restic/restic/releases/download/v0.12.0"
      packages:
        - file: "restic_0.12.0_linux_amd64.bz2"
          uncompress: true
      paths:
        - target: "{{ bkp_restic_base['paths']['root'] }}"
          owner: "{{ bkp_restic_base['access']['owner'] }}"
          group: "{{ bkp_restic_base['access']['group'] }}"
          mode: "{{ bkp_restic_base['access']['mode']['dir'] }}"
        - target: "{{ bkp_restic_base['paths']['bin'] }}"
          owner: "{{ bkp_restic_base['access']['owner'] }}"
          group: "{{ bkp_restic_base['access']['group'] }}"
          mode: "{{ bkp_restic_base['access']['mode']['dir'] }}"
        - target: "{{ bkp_restic_base['paths']['etc'] }}"
          owner: "{{ bkp_restic_base['access']['owner'] }}"
          group: "{{ bkp_restic_base['access']['group'] }}"
          mode: "{{ bkp_restic_base['access']['mode']['dir'] }}"
      promotion:
        - target: "{{ bkp_restic_base['run']['restic'] }}"
          source: "restic_0.12.0_linux_amd64"
          owner: "{{ bkp_restic_base['access']['owner'] }}"
          group: "{{ bkp_restic_base['access']['group'] }}"
          mode: "{{ bkp_restic_base['access']['mode']['exe'] }}"
...
