---
- name: "Application / ShotCut / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_shotcut_platforms

- name: "Application / ShotCut / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_shotcut_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_shotcut"
    - app_shotcut['resolve_prereq']
...
