---
# WARNING: automation, security, application:  required for molecule testing
roles: []
collections:
  - name: "../../../../../build/dev/serdigital64-automation.tar.gz"
    type: "file"
  - name: "../../../../../build/dev/serdigital64-security.tar.gz"
    type: "file"
  - name: "../../../../../build/dev/serdigital64-application.tar.gz"
    type: "file"
  - name: "../../../../../build/dev/serdigital64-system.tar.gz"
    type: "file"
...
