---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_gui_cinnamon"

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{
          sys_gui_cinnamon_base['paths']['users'] + '/' +
          test_sys_gui_cinnamon_users[0]['user'] + '/' +
          test_sys_gui_cinnamon_users[0]['theme'] }}"
      register: file_stat

    - name: "Verify path is created"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
