---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "cnt_podman"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - cnt_podman_platforms is defined
          - cnt_podman_profiles is defined
          - cnt_podman_application is defined
...
