---
- name: "DevOps / Jenkins / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dops_jenkins_platforms

- name: "DevOps / Jenkins / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dops_jenkins_os_family + '.yml' }}"

- name: "DevOps / Jenkins / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dops_jenkins_prerequisite.yml"
  when:
    - "'resolve_prereq' in dops_jenkins"
    - dops_jenkins['resolve_prereq']
...
