---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "app_darktable"

    - name: "Load Package manager definitions"
      ansible.builtin.include_role:
        public: true
        name: "serdigital64.system.sys_repository"

    - name: "Detect installed apps"
      ansible.builtin.command:
        argv:
          - "{{ sys_repository_base['run']['flatpak'] }}"
          - "--system"
          - "--app"
          - "--columns=application"
          - "list"
      changed_when: false
      register: app_list

    - name: "Verify app is installed"
      ansible.builtin.assert:
        that:
          - app_list['stdout_lines'] is search(
              app_darktable_profiles['flatpak']['latest']['packages'][0]['name']
            )
...
