---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "bkp_restic"

    - name: "Detect restic status"
      ansible.builtin.stat:
        path: "{{ bkp_restic_base['run']['restic'] }}"
      register: file_status

    - name: "Verify the binary was installed"
      ansible.builtin.assert:
        that:
          - file_status['stat']['exists']
...
