---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Setup sudoers"
      vars:
        sys_sudo:
          setup: true
        sys_sudo_rules:
          user:
            - name: "test"
              rule: "ALL=(ALL) NOPASSWD: ALL"
              present: true
      ansible.builtin.include_role:
        name: "sys_sudo"
...
