---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_sudo"

    - name: "Detect line in sudoers"
      register: test_line
      ansible.builtin.command:
        argv:
          - "/usr/bin/grep"
          - "test ALL=(ALL) NOPASSWD: ALL"
          - "{{ sys_sudo_base['etc']['sudoers'] }}"
      changed_when: false

    - name: "Verify the line was added"
      ansible.builtin.assert:
        that:
          - test_line['stdout'] == "test ALL=(ALL) NOPASSWD: ALL"
...
