---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_sudo"

    - name: "Verify required packages are deployed"
      ansible.builtin.assert:
        that:
          - item in ansible_facts['packages']
      loop:
        - "sudo"
...
