---
galaxy_info:
  role_name: "sys_package"
  author: "serdigital64"
  description: "Manage application package provisioning"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "package"
    - "rpm"
    - "deb"
    - "snap"
    - "flatpak"
    - "git"
dependencies: []
...
