---
- name: "DevOps / GIT / Server / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dops_git_server_platforms

- name: "DevOps / GIT / Server / Initialize / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - dops_git_server_paths is defined

- name: "DevOps / GIT / Server / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dops_git_server_os_family + '.yml' }}"

- name: "DevOps / GIT / Server / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dops_git_server_prerequisite.yml"
  when:
    - "'resolve_prereq' in dops_git_server"
    - dops_git_server['resolve_prereq']
...
