---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare"
      vars:
        dops_git_client:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "dops_git_client"

    - name: "Create test user"
      become: true
      ansible.builtin.user:
        create_home: true
        system: false
        state: "present"
        name: "test"
...
