---
sys_fonts_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

sys_fonts_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

sys_fonts_base_common:
  files:
    meslo_r: "MesloLGS NF Regular.ttf"
    meslo_b: "MesloLGS NF Bold.ttf"
    meslo_i: "MesloLGS NF Italic.ttf"
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"

sys_fonts_application:
  config:
    name: "config"
    type: "distro"
    version: "latest"
    installed: true
  urw:
    name: "urw"
    type: "distro"
    version: "latest"
    installed: true
  meslo:
    name: "meslo"
    type: "binary"
    version: "latest"
    installed: true

sys_fonts_profiles_common:
  meslo:
    binary:
      latest:
        origin: "https://github.com/romkatv/powerlevel10k-media/raw/master"
        packages:
          - file: "{{ sys_fonts_base_common['files']['meslo_r'] }}"
            uncompress: false
          - file: "{{ sys_fonts_base_common['files']['meslo_b'] }}"
            uncompress: false
          - file: "{{ sys_fonts_base_common['files']['meslo_i'] }}"
            uncompress: false
        paths:
          - target: "{{ sys_fonts_base['paths']['fonts_meslo'] }}"
            owner: "{{ sys_fonts_base['access']['user']['owner'] }}"
            mode: "{{ sys_fonts_base['access']['mode']['dir'] }}"
        promotion:
          - target: "{{ sys_fonts_base['paths']['fonts_meslo'] }}"
            source: "{{ sys_fonts_base_common['files']['meslo_r'] }}"
            owner: "{{ sys_fonts_base['access']['user']['owner'] }}"
            mode: "{{ sys_fonts_base['access']['mode']['file'] }}"
          - target: "{{ sys_fonts_base['paths']['fonts_meslo'] }}"
            source: "{{ sys_fonts_base_common['files']['meslo_b'] }}"
            owner: "{{ sys_fonts_base['access']['user']['owner'] }}"
            mode: "{{ sys_fonts_base['access']['mode']['file'] }}"
          - target: "{{ sys_fonts_base['paths']['fonts_meslo'] }}"
            source: "{{ sys_fonts_base_common['files']['meslo_i'] }}"
            owner: "{{ sys_fonts_base['access']['user']['owner'] }}"
            mode: "{{ sys_fonts_base['access']['mode']['file'] }}"

# sys_fonts___deploy_font
# sys_fonts___prepare_path
...
