---
sys_fonts_base:
  access: "{{ sys_fonts_base_common['access'] }}"
  files: "{{ sys_fonts_base_common['files'] }}"
  paths:
    fonts_system: "/usr/share/fonts"
    fonts_local: "/usr/local/share/fonts"
    fonts_meslo: "/opt/fonts-meslo"
  run:
    fc_cache: "/usr/bin/fc-cache"

sys_fonts_profiles:
  config:
    distro:
      latest:
        packages:
          - name: "fontconfig"
  urw:
    distro:
      latest:
        packages:
          - name: "urw-base35-fonts"
  meslo: "{{ sys_fonts_profiles_common['meslo']  }}"

sys_fonts_repository_custom_yum: []
sys_fonts_repository_custom_apt: []

sys_fonts_repository_catalog_distro: {}
sys_fonts_repository_catalog_yum: {}
sys_fonts_repository_catalog_apt: {}
...
