---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create test user"
      become: true
      ansible.builtin.user:
        create_home: true
        system: false
        state: "present"
        name: "test"

    - name: "Create key path"
      become: true
      ansible.builtin.file:
        state: "directory"
        mode: "0700"
        path: "/home/test/keys"

    - name: "Create key known_hosts file"
      become: true
      ansible.builtin.file:
        state: "touch"
        mode: "0600"
        path: "/home/test/keys/known_hosts"

    - name: "Install openssh client"
      vars:
        sec_openssh_client:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.security.sec_openssh_client"

...
