---
- name: "DevOps / GIT / Client / Setup / Create default user configuration ()"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    mode: "{{ dops_git_client_base['access']['mode']['file'] }}"
    owner: "{{ dops_git_client___setup_user['name'] }}"
    group: "{{ dops_git_client___setup_user['group'] }}"
    src: "{{ dops_git_client_base['templates']['usr_config'] }}"
    dest: "{{ dops_git_client___setup_user['home'] + '/' + dops_git_client_base['etc']['usr_gitconfig'] }}"
  loop: "{{ dops_git_client_users }}"
  loop_control:
    loop_var: "dops_git_client___setup_user"
...
