---
- name: "Web / HAProxy / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in web_haproxy_platforms

- name: "Web / HAProxy / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + web_haproxy_os_family + '.yml' }}"

- name: "Web / HAProxy / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "web_haproxy_prerequisite.yml"
  when:
    - web_haproxy['resolve_prereq'] is defined
    - web_haproxy['resolve_prereq']
...
