---
- name: "Cloud / Azure / CLI / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in cloud_azure_cli_platforms

- name: "Cloud / Azure / CLI / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "platform-{{ cloud_azure_cli_os_family }}.yml"

- name: "Cloud / Azure / CLI / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "cloud_azure_cli_prerequisite.yml"
  when:
    - "'resolve_prereq' in cloud_azure_cli"
    - cloud_azure_cli['resolve_prereq']
...
