---
- name: "Prepare"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create test user"
      become: true
      ansible.builtin.user:
        create_home: true
        system: false
        state: "present"
        name: "{{ test_user }}"

    - name: "Deploy required packages"
      vars:
        sys_mc:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "sys_mc"
...
