---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_mc"

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{ test_home + '/' + sys_mc_base['etc']['ini'] }}"
      register: file_stat

    - name: "Verify path is created"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
