---
- name: "DevOps / ShellCheck / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dops_shellcheck_platforms

- name: "DevOps / ShellCheck / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dops_shellcheck_os_family + '.yml' }}"

- name: "DevOps / ShellCheck / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dops_shellcheck_prerequisite.yml"
  when:
    - dops_shellcheck['resolve_prereq'] is defined
    - dops_shellcheck['resolve_prereq']
...
