---
- name: "DevOps / ShellCheck / Prerequisite / Prepare package managers"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
    sys_repository_managers:
      flatpak: "{{ dops_shellcheck_application['type'] == 'flatpak' }}"
      snap: "{{ dops_shellcheck_application['type'] == 'snap' }}"
      git: "{{ dops_shellcheck_application['type'] == 'git' }}"
      pip: "{{ dops_shellcheck_application['type'] == 'pip' }}"
    sys_repository_catalog_distro: "{{ dops_shellcheck_repository_catalog_distro }}"
    sys_repository_catalog_yum: "{{ dops_shellcheck_repository_catalog_yum }}"
    sys_repository_catalog_apt: "{{ dops_shellcheck_repository_catalog_apt }}"
    sys_repository_custom_yum: "{{ dops_shellcheck_repository_custom_yum }}"
    sys_repository_custom_apt: "{{ dops_shellcheck_repository_custom_apt }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"

- name: "DevOps / ShellCheck / Prerequisite / Prepare archive manager"
  vars:
    bkp_archive:
      deploy: true
  ansible.builtin.include_role:
    name: "serdigital64.backup.bkp_archive"

- name: "DevOps / ShellCheck / Prerequisite / Prepare package installer"
  vars:
    sys_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
