---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_package:
          provision: true
        sys_package_application:
          name: "ibmcloud"
          type: "binary"
          version: "v2_0_0"
          installed: true
        sys_package_profiles:
          binary:
            v2_0_0:
              origin: "https://download.clis.cloud.ibm.com/ibm-cloud-cli/2.0.0/binaries"
              packages:
                - file: "IBM_Cloud_CLI_2.0.0_linux_amd64.tgz"
                  uncompress: true
              paths:
                - target: "{{ test_target }}"
                  owner: "root"
                  mode: "0755"
              promotion:
                - target: "{{ test_target }}"
                  source: "IBM_Cloud_CLI/{{ test_app_bin }}"
                  mode: "0755"
                  owner: "root"
      ansible.builtin.include_role:
        name: "sys_package"
...
