---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create test user and group"
      vars:
        sys_user:
          setup: true
        sys_user_groups:
          - name: "test100"
            gid: "10123"
            system: false
      ansible.builtin.include_role:
        name: "sys_user"
...
