---
hpv_libvirt_client_base:
  run:
    virsh: "/usr/bin/virsh"

hpv_libvirt_client_profiles:
  bin:
    distro:
      latest:
        packages:
          - name: "libvirt-client"
  dev:
    distro:
      latest:
        packages:
          - name: "libvirt-devel"

hpv_libvirt_client_repository_custom_yum: []
hpv_libvirt_client_repository_custom_apt: []

hpv_libvirt_client_repository_catalog_distro: {}
hpv_libvirt_client_repository_catalog_yum: {}
hpv_libvirt_client_repository_catalog_apt: {}
...
