---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Setup"
      vars:
        auto_aplatform64:
          setup: true
        auto_ansible_control_site: "{{ test_site }}"
        auto_ansible_control_users: "{{ test_control_users }}"
        auto_ansible_control_paths: "{{ test_control_paths }}"
        auto_ansible_control_managed: "{{ test_control_managed }}"
      ansible.builtin.include_role:
        name: "auto_aplatform64"
...
