---
app_xmind_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_xmind_profiles:
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "net.xmind.ZEN"
  snap:
    latest:
      packages:
        - name: "xmind"
...
