---
- name: "Development / Java / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dev_java_platforms

- name: "Development / Java / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"

- name: "Development / Java / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dev_java_prerequisite.yml"
  when:
    - "'resolve_prereq' in dev_java"
    - dev_java['resolve_prereq']
...
