---
- name: "Development / Java / Initialize"
  ansible.builtin.include_tasks:
    file: "dev_java_initialize.yml"

- name: "Development / Java / Deploy"
  ansible.builtin.include_tasks:
    file: "dev_java_deploy.yml"
  when:
    - "'deploy' in dev_java"
    - "dev_java['deploy']"

- name: "Development / Java / Finalize"
  ansible.builtin.include_tasks:
    file: "dev_java_finalize.yml"
...
