---
- name: "Application / Spotify / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_spotify_platforms

- name: "Application / Spotify / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_spotify_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_spotify"
    - app_spotify['resolve_prereq']
...
