---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "dev_opencl"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - dev_opencl_platforms is defined
          - dev_opencl_profiles is defined
          - dev_opencl_application is defined
...
