---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_package:
          provision: true
        sys_package_application:
          name: "fonts"
          type: "binary"
          version: "latest"
          installed: true
        sys_package_profiles:
          binary:
            latest:
              origin: "https://github.com/romkatv/powerlevel10k-media/raw/master"
              packages:
                - file: "{{ 'MesloLGS NF Regular.ttf' }}"
                  uncompress: false
                - file: "{{ 'MesloLGS NF Bold.ttf' }}"
                  uncompress: false
              paths:
                - target: "{{ test_target }}"
                  owner: "root"
                  mode: "0755"
              promotion:
                - target: "{{ test_target }}"
                  source: "MesloLGS NF Regular.ttf"
                  mode: "0644"
                  owner: "root"
                - target: "{{ test_target }}"
                  source: "MesloLGS NF Bold.ttf"
                  mode: "0644"
                  owner: "root"
      ansible.builtin.include_role:
        name: "sys_package"
...
