---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sec_key_ssh"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - sec_key_ssh_platforms is defined
          - sec_key_ssh_os_family is defined
          - sec_key_ssh_base is defined
...
