---
- name: "System / Sudo / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sys_sudo_application }}"
    sys_package_profiles: "{{ sys_sudo_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
