---
dev_python_base:
  files: "{{ dev_python_base_common['files'] }}"
  access: "{{ dev_python_base_common['access'] }}"
  run:
    python_3_10: &dev_python_base_run_python_3_10
      "/usr/bin/python3.9"
    python_latest: *dev_python_base_run_python_3_10

dev_python_profiles:
  distro:
    v3_10: &dev_python_profiles_distro_v3_10
      packages:
        - name: "python3"
        - name: "python3-pip"
        - name: "python3-wheel"
        - name: "python3-setuptools"
        - name: "which"             # Required by pip
        # venv already included in the main python package
    latest: *dev_python_profiles_distro_v3_10

dev_python_repository_custom_yum: []
dev_python_repository_custom_apt: []

dev_python_repository_catalog_distro: {}
dev_python_repository_catalog_yum: {}
dev_python_repository_catalog_apt: {}
...
