---
dev_python_base:
  files: "{{ dev_python_base_common['files'] }}"
  access: "{{ dev_python_base_common['access'] }}"
  run:
    python_3_8:
      "/usr/bin/python3.8"
    python_3_9: &dev_python_base_run_python_3_9
      "/usr/bin/python3.9"
    python_latest: *dev_python_base_run_python_3_9

dev_python_profiles:
  distro:
    v3_8:
      packages:
        - name: "python38"
        - name: "python38-pip"
        - name: "python38-setuptools"
        - name: "python38-wheel"
        - name: "which"             # Required by pip
        # venv already included in the main python package
    v3_9: &dev_python_profiles_distro_v3_9
      packages:
        - name: "python39"
        - name: "python39-pip"
        - name: "python39-setuptools"
        - name: "python39-wheel"
        - name: "which"             # Required by pip
        # venv already included in the main python package
    latest: *dev_python_profiles_distro_v3_9

dev_python_repository_custom_yum: []
dev_python_repository_custom_apt: []

dev_python_repository_catalog_distro: {}
dev_python_repository_catalog_yum: {}
dev_python_repository_catalog_apt: {}
...
