---
dev_python_base:
  files: "{{ dev_python_base_common['files'] }}"
  access: "{{ dev_python_base_common['access'] }}"
  run:
    python_3_8:
      "/usr/bin/python3.8"
    python_3_9: &dev_python_base_run_python_3_9
      "/usr/bin/python3.9"
    python_latest: *dev_python_base_run_python_3_9

dev_python_profiles:
  distro:
    v3_8:
      packages:
        - name: "python3.8"
        - name: "python3.8-venv"
        - name: "python3-pip"
        - name: "python3-setuptools"
        - name: "python3-wheel"
    v3_9: &dev_python_profiles_distro_v3_9
      packages:
        - name: "python3.9"
        - name: "python3.9-venv"
        - name: "python3-setuptools"
        - name: "python3-wheel"
        - name: "python3-pip"
    latest: *dev_python_profiles_distro_v3_9

dev_python_repository_custom_yum: []
dev_python_repository_custom_apt: []

dev_python_repository_catalog_distro: {}
dev_python_repository_catalog_yum: {}
dev_python_repository_catalog_apt: {}
...
