---
app_spotify_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_spotify_profiles:
  snap:
    latest:
      packages:
        - name: "spotify"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "com.spotify.Client"
...
