---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      vars:
        auto_ansible_control_users: "{{ test_control_users }}"
        auto_ansible_control_paths: "{{ test_control_paths }}"
      ansible.builtin.include_role:
        public: true
        name: "auto_ansible_control"

    - name: "Load role variables for OpenSSH"
      ansible.builtin.include_role:
        public: true
        name: "serdigital64.security.sec_openssh_client"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - sec_openssh_client_base['run']['sshpass'] is defined
...
