---
galaxy_info:
  role_name: "db_postgresql_client"
  author: "serdigital64"
  description: "Manage provisioning of PostgreSQL client"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "postgresql"
dependencies: []
...
