---
galaxy_info:
  role_name: "stg_nfs_server"
  author: "serdigital64"
  description: "Manage the Linux NFS server"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "nfs"
dependencies: []
...
