---
- name: "Development / Tools / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dev_tools_platforms

- name: "Development / Tools / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dev_tools_os_family + '.yml' }}"

- name: "Development / Tools / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dev_tools_prerequisite.yml"
  when:
    - "'resolve_prereq' in dev_tools"
    - dev_tools['resolve_prereq']
...
