---
- name: "Development / Python / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dev_python_platforms

- name: "Development / Python / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"
  changed_when: false

- name: "Development / Python / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dev_python_prerequisite.yml"
  when:
    - "'resolve_prereq' in dev_python"
    - dev_python['resolve_prereq']
...
