---
galaxy_info:
  role_name: "cloud_foundry_cli"
  author: "serdigital64"
  description: "Manage provisioning of Cloud Foundry CLI"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "cloudfoundry"
dependencies: []
...
