---
dops_jenkins_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

dops_jenkins_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

dops_jenkins_base_common:
  paths:
    var: "/var/lib/jenkins"
  access:
    owner: "root"
    group: "root"
    mode:
      file: "0600"
  templates:
    jenkins_sh: "jenkins.sh.j2"

dops_jenkins_firewall_predefined:
  id: "jenkins_console"

# Jenkins server predefined options.
dops_jenkins_server_predefined:
  home: "{{ dops_jenkins_base_common['paths']['var'] }}"
  java_cmd: ""
  user: "jenkins"
  java_options: "-Djava.awt.headless=true"
  enable_access_log: "no"
  https_port: ""
  https_listen_address: ""
  handler_max: "100"
  handler_idle: "20"

dops_jenkins_alert_ansible_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.devops.dops_jenkins. Do not modify."
...
