---
auto_ansible_control_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

auto_ansible_control_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

auto_ansible_control_base:
  access:
    owner: "{{ auto_ansible_control_users['control']['name'] }}"
    group: "{{ auto_ansible_control_users['control']['name'] }}"
    mode:
      exe: "0750"
      file: "0640"
      dir: "0750"
  paths:
    root: "{{ auto_ansible_control_paths['root'] }}"
    bin: "{{ auto_ansible_control_paths['root'] + '/bin' }}"
    docs: "{{ auto_ansible_control_paths['root'] + '/docs' }}"
    collections: "{{ auto_ansible_control_paths['root'] + '/collections' }}"
    filter_plugins: "{{ auto_ansible_control_paths['root'] + '/filter_plugins' }}"
    inventories: "{{ auto_ansible_control_paths['root'] + '/inventories' }}"
    library: "{{ auto_ansible_control_paths['root'] + '/library' }}"
    module_utils: "{{ auto_ansible_control_paths['root'] + '/module_utils' }}"
    templates: "{{ auto_ansible_control_paths['root'] + '/templates' }}"
    vars: "{{ auto_ansible_control_paths['root'] + '/vars' }}"
    etc: "{{ auto_ansible_control_paths['root'] + '/etc' }}"
    etc_groups: "{{ auto_ansible_control_paths['root'] + '/etc/groups' }}"
    etc_cfg: "{{ auto_ansible_control_paths['root'] + '/etc/cfg' }}"
    etc_keys: "{{ auto_ansible_control_paths['root'] + '/etc/keys' }}"
    etc_tokens: "{{ auto_ansible_control_paths['root'] + '/etc/tokens' }}"
    files: "{{ auto_ansible_control_paths['root'] + '/files' }}"
    files_groups: "{{ auto_ansible_control_paths['root'] + '/files/groups' }}"
    roles: "{{ auto_ansible_control_paths['root'] + '/roles' }}"
    playbooks: "{{ auto_ansible_control_paths['root'] + '/playbooks' }}"
    tests: "{{ auto_ansible_control_paths['root'] + '/tests' }}"
    var: "{{ auto_ansible_control_paths['var'] }}"
    var_groups: "{{ auto_ansible_control_paths['var'] + '/groups' }}"
    cache: "{{ auto_ansible_control_paths['var'] + '/cache' }}"
    tmp: "{{ auto_ansible_control_paths['var'] + '/tmp' }}"
    logs: "{{ auto_ansible_control_paths['var'] + '/logs' }}"
    persistence: "{{ auto_ansible_control_paths['var'] + '/persistence' }}"
    site_bin: "{{
      auto_ansible_control_paths['root'] +
      '/bin/' +
      auto_ansible_control_site
      }}"
    site_docs: "{{
      auto_ansible_control_paths['root'] +
      '/docs/' +
      auto_ansible_control_site
      }}"
    site_inventories: "{{
      auto_ansible_control_paths['root'] +
      '/inventories/' +
      auto_ansible_control_site
      }}"
    site_files: "{{
      auto_ansible_control_paths['root'] +
      '/files/' +
      auto_ansible_control_site
      }}"
    site_cfg: "{{
      auto_ansible_control_paths['root'] +
      '/etc/cfg/'
      + auto_ansible_control_site
      }}"
    site_playbooks: "{{
      auto_ansible_control_paths['root'] +
      '/playbooks/' +
      auto_ansible_control_site
      }}"
    site_tests: "{{
      auto_ansible_control_paths['root'] +
      '/tests/' +
      auto_ansible_control_site
      }}"
    site_keys: "{{
      auto_ansible_control_paths['root'] +
      '/etc/keys/'
      + auto_ansible_control_site
      }}"
    site_vars: "{{
      auto_ansible_control_paths['root'] +
      '/vars/'
      + auto_ansible_control_site
      }}"
    site_templates: "{{
      auto_ansible_control_paths['root'] +
      '/templates/'
      + auto_ansible_control_site
      }}"
    site_roles: "{{
      auto_ansible_control_paths['root'] +
      '/roles/'
      + auto_ansible_control_site
      }}"
    site_logs: "{{
      auto_ansible_control_paths['var'] +
      '/logs/' +
      auto_ansible_control_site
      }}"
    site_tmp: "{{
      auto_ansible_control_paths['var'] +
      '/tmp/' +
      auto_ansible_control_site
      }}"
    site_cache: "{{
      auto_ansible_control_paths['var'] +
      '/cache/' +
      auto_ansible_control_site
      }}"
    site_persistence: "{{
      auto_ansible_control_paths['var'] +
      '/persistence/' +
      auto_ansible_control_site
      }}"
    site_etc_groups: "{{
      auto_ansible_control_paths['root'] +
      '/etc/groups/' +
      auto_ansible_control_site
      }}"
    site_var_groups: "{{
      auto_ansible_control_paths['var'] +
      '/groups/' +
      auto_ansible_control_site
      }}"
    site_files_groups: "{{
      auto_ansible_control_paths['root'] +
      '/files/' +
      auto_ansible_control_site +
      '/groups'
      }}"
    site_group_vars: "{{
      auto_ansible_control_paths['root'] +
      '/inventories/' +
      auto_ansible_control_site +
      '/group_vars'
      }}"
    site_group_vars_all: "{{
      auto_ansible_control_paths['root'] +
      '/inventories/' +
      auto_ansible_control_site +
      '/group_vars/all'
      }}"
    site_host_vars: "{{
      auto_ansible_control_paths['root'] +
      '/inventories/' +
      auto_ansible_control_site +
      '/host_vars'
      }}"
  files:
    control_secret: "{{
      auto_ansible_control_paths['root'] +
      '/etc/keys/' +
      auto_ansible_control_site +
      '/control.secret'
      }}"
    known_hosts: "{{
      auto_ansible_control_paths['root'] +
      '/etc/keys/' +
      auto_ansible_control_site +
      '/known_hosts'
      }}"
    managed_private_key: "{{
      auto_ansible_control_paths['root'] +
      '/etc/keys/' +
      auto_ansible_control_site +
      '/managed_private_key'
      }}"
    managed_public_key: "{{
      auto_ansible_control_paths['root'] +
      '/etc/keys/' +
      auto_ansible_control_site +
      '/managed_private_key.pub'
      }}"
    ansible_common: "{{
      auto_ansible_control_paths['root'] +
      '/inventories/' +
      auto_ansible_control_site +
      '/group_vars/all/ansible_common.yml'
      }}"
    ansible_inventory: "{{
      auto_ansible_control_paths['root'] +
      '/inventories/' +
      auto_ansible_control_site +
      '/hosts.ini'
      }}"
    ansible_cfg: "{{
      auto_ansible_control_paths['root'] +
      '/etc/cfg/' +
      auto_ansible_control_site +
      '/ansible.cfg'
      }}"
    ansible_debug_cfg: "{{
      auto_ansible_control_paths['root'] +
      '/etc/cfg/' +
      auto_ansible_control_site +
      '/ansible-debug.cfg'
      }}"
    galaxy_token: "{{
      auto_ansible_control_paths['root'] +
      '/etc/tokens/galaxy.token'
      }}"
    ansible_log: "{{
      auto_ansible_control_paths['var'] +
      '/logs/' +
      auto_ansible_control_site +
      '/ansible.log'
      }}"
    ansible_control_env: "{{
      auto_ansible_control_paths['root'] +
      '/bin/' +
      auto_ansible_control_site +
      '/ansible_control.env'
      }}"
  templates:
    ansible_inventory: "hosts.ini.j2"
    ansible_cfg: "ansible.cfg.j2"
    ansible_debug_cfg: "ansible-debug.cfg.j2"
    ansible_control_env: "ansible_control.env.j2"
    ansible_common: "ansible_common.yml.j2"

auto_ansible_control_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.automation.auto_ansible_control. Do not modify."

#auto_ansible_control___path: ~
...
