---
- name: "Hypervisor / LibVirt / Client / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in hpv_libvirt_client_platforms

- name: "Hypervisor / LibVirt / Client / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + hpv_libvirt_client_os_family + '.yml' }}"

- name: "Hypervisor / LibVirt / Client / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "hpv_libvirt_client_prerequisite.yml"
  when:
    - "'resolve_prereq' in hpv_libvirt_client"
    - hpv_libvirt_client['resolve_prereq']
...
