---
app_obs_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_obs_profiles:
  snap:
    latest:
      packages:
        - name: "obs-studio"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "com.obsproject.Studio"
...
