---
- name: "Development / NodeJS / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dev_nodejs_platforms

- name: "Development / NodeJS / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dev_nodejs_os_family + '.yml' }}"

- name: "Development / NodeJS / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dev_nodejs_prerequisite.yml"
  when:
    - "'resolve_prereq' in dev_nodejs"
    - dev_nodejs['resolve_prereq']
...
