---
# Define supported platforms
stg_autofs_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
stg_autofs_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

# Define common paths
stg_autofs_base_common:
  paths:
    auto_master_d: "/etc/auto.master.d"
    auto_custom_d: "/etc/auto.custom.d"
    root: "{{ stg_autofs_server_options['root'] | default( stg_autofs_server_presets['root'] ) }}"
  etc:
    auto_master: "/etc/auto.master"
    autofs_conf: "/etc/autofs.conf"
    auto_net: "/etc/auto.net"
    auto_misc: "/etc/auto.misc"
    auto_smb: "/etc/auto.smb"
  templates:
    autofs_conf: "autofs.conf.j2"
    auto_master: "auto.master.j2"
    custom_autofs: "custom.autofs.j2"
    auto_custom: "auto.custom.j2"
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"

# Available logging options
stg_autofs_logging:
  - "none"
  - "verbose"
  - "debug"

# Define subsystem server options. This will be used along with stg_autofs_server_options
stg_autofs_server_presets:
  timeout: "100"
  logging: "none"
  root: "/autofs"

stg_autofs_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.storage.stg_autofs. Do not modify."

# Loop variables
# stg_autofs___prepare_path
# stg_autofs___setup_path
# stg_autofs___setup_file
# stg_autofs___provision_share
# stg_autofs___provision_map
...
