---
- name: "Manage Cloud Realm"
  hosts: cloud_realm
  gather_facts: false

  pre_tasks:

    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

  tasks:

    - name: "Manage AWS Realm"
      vars:
        cloud_aws_realm:
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.cloud.cloud_aws_realm"
      when:
        - cloud_realm_provider['aws'] is defined
        - cloud_realm_provider['aws']
...
