---
- name: "Manage Ansible Control Node"
  hosts: "ansible_control_nodes"
  gather_facts: false

  pre_tasks:

    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

  tasks:

    - name: "Setup Ansible Control Node"
      vars:
        auto_ansible_control:
          prepare: true
          setup: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_ansible_control"

    - name: "Setup A:Platform64"
      vars:
        auto_aplatform64:
          prepare: true
          setup: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_aplatform64"

    - name: "Setup Ansible Managed Node"
      vars:
        auto_ansible_node:
          prepare: true
          deploy: true
          provision: true
          bootstrap: false
      ansible.builtin.include_role:
        name: "serdigital64.automation.auto_ansible_node"
...
