---
- name: "Manage Jenkins Controller Nodes"
  hosts: "jenkins_controller_nodes"
  gather_facts: false

  pre_tasks:
    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare package repositories"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          setup: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"

    - name: "Prepare archive manager"
      vars:
        bkp_archive:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.backup.bkp_archive"

    - name: "Prepare package installer"
      vars:
        sys_package:
          prepare: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_package"

  tasks:
    - name: "Prepare OS subsystem manager"
      vars:
        sys_subsystem:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_subsystem"
      when:
        - jenkins_controller_nodes_apps['jenkins'] is defined
        - jenkins_controller_nodes_apps['jenkins']

    - name: "Provision OpenJDK 11 for Jenkins"
      vars:
        dev_java:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.development.dev_java"
      when:
        - jenkins_controller_nodes_apps['jenkins'] is defined
        - jenkins_controller_nodes_apps['jenkins']

    - name: "Provision Jenkins Controller"
      vars:
        dops_jenkins:
          deploy: true
          setup: true
          control: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_jenkins"
      when:
        - jenkins_controller_nodes_apps['jenkins'] is defined
        - jenkins_controller_nodes_apps['jenkins']
...
