---
- name: "Manage Test Nodes"
  hosts: "test_nodes"
  gather_facts: false

  pre_tasks:
    - name: "Discover Target Platform"
      ansible.builtin.setup:
        gather_subset: "min"

    - name: "Prepare package repositories"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          setup: true
          provision: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_repository"

    - name: "Prepare archive manager"
      vars:
        bkp_archive:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.backup.bkp_archive"

    - name: "Prepare package installer"
      vars:
        sys_package:
          prepare: true
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_package"

  tasks:
    - name: "Provision AnsibleLint"
      vars:
        dops_ansiblelint:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_ansiblelint"
      when:
        - test_nodes_apps['ansiblelint'] is defined
        - test_nodes_apps['ansiblelint']

    - name: "Provision Bats Core"
      vars:
        dops_batscore:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_batscore"
      when:
        - test_nodes_apps['batscore'] is defined
        - test_nodes_apps['batscore']

    - name: "Provision Molecule"
      vars:
        dops_molecule:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_molecule"
      when:
        - test_nodes_apps['molecule'] is defined
        - test_nodes_apps['molecule']

    - name: "Provision ShellCheck"
      vars:
        dops_shellcheck:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_shellcheck"
      when:
        - test_nodes_apps['shellcheck'] is defined
        - test_nodes_apps['shellcheck']

    - name: "Provision YAMLLint"
      vars:
        dops_yamllint:
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.devops.dops_yamllint"
      when:
        - test_nodes_apps['yamllint'] is defined
        - test_nodes_apps['yamllint']
...
