---
app_skype_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_skype_profiles:
  snap:
    latest:
      packages:
        - name: "skype"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "com.skype.Client"
...
