---
sys_gui_cinnamon_platforms:
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

sys_gui_cinnamon_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

sys_gui_cinnamon_catalog_user:
  - "adapta_nokto_v1"

sys_gui_cinnamon_application:
  name: "cinnamon"
  type: "distro"
  version: "latest"
  installed: true

# Define common paths
sys_gui_cinnamon_base_common:
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates:
    adapta_nokto_v1: "theme_adapta_nokto_v1.toml.j2"
  etc: {}
  files: {}
  run: {}
  paths:
    var: "/var/opt/sys_gui_cinnamon"

sys_gui_cinnamon_alert_ansible_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.system.sys_gui_cinnamon. Do not modify."

# Temporary loop variables
# sys_gui_cinnamon___prepare_path
...
