---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "cloud_aws_cli"

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{ cloud_aws_cli_base['run']['aws'] }}"
      register: file_stat

    - name: "Verify app is installed"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
