---
- name: "Application / Skype / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_skype_platforms

- name: "Application / Skype / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_skype_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_skype"
    - app_skype['resolve_prereq']
...
