---
galaxy_info:
  role_name: "dops_batscore"
  author: "serdigital64"
  description: "Manage provisioning of Bats Core"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "batscore"
dependencies: []
...
