---
# Supported archive formats
bkp_archive_formats:
  common:
    - "application/x-compress"
    - "application/x-gtar"
    - "application/x-gzip"
    - "application/zip"
    - "application/gtar"
    - "application/gzip"
  xz:
    - "application/x-xz"
  bzip2:
    - "application/x-bzip2"

bkp_archive_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

bkp_archive_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- elif
      ( ansible_distribution == 'Debian' )
  -%}
    {{ 'Debian' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

#bkp_archive___provision_item: ~
bkp_archive___provision_archive_file: ~
bkp_archive___provision_content_file: ~
bkp_archive___provision_extraction_result: ~
bkp_archive___provision_movement_result: ~
bkp_archive___provision_content_type: ~
bkp_archive___provision_content_mode: ~
bkp_archive___provision_archive_encapsulated: ""
...
