---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "stg_nfs_client"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - stg_nfs_client_platforms is defined
          - stg_nfs_client_profiles is defined
          - stg_nfs_client_application is defined
...
