---
auto_ansible_node_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

auto_ansible_node_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'Fedora' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

auto_ansible_node_base:
  paths:
    ssh: "{{ auto_ansible_node_user['home'] + '/.ssh' }}"
    home: "{{ auto_ansible_node_user['home'] }}"
  access:
    owner: "{{ auto_ansible_node_user['name'] }}"
    group: "{{ auto_ansible_node_user['group'] }}"
    mode:
      dir: "0700"
      file: "0600"
  run:
    visudo: "/usr/sbin/visudo"
  files:
    sudoers: "/etc/sudoers"
    authorized_keys: "{{ auto_ansible_node_user['home'] + '/.ssh/authorized_keys' }}"

auto_ansible_node_privilege: "ALL=(ALL) NOPASSWD: ALL"

#auto_ansible_node___path: ~
...
