---
- name: "DevOps / AnsibleLint / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dops_ansiblelint_platforms

- name: "DevOps / AnsibleLint / Initialize / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "required parameters are missing ({{
      dops_ansiblelint_paths | default('dops_ansiblelint_paths') }} / {{
      dops_ansiblelint_owners | default('dops_ansiblelint_owners') }})"
    that:
      - dops_ansiblelint_paths is defined
      - dops_ansiblelint_owners is defined

- name: "DevOps / AnsibleLint / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dops_ansiblelint_os_family + '.yml' }}"

- name: "DevOps / AnsibleLint / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dops_ansiblelint_prerequisite.yml"
  when:
    - dops_ansiblelint['resolve_prereq'] is defined
    - dops_ansiblelint['resolve_prereq']
...
