---
app_vscode_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_vscode_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

app_vscode_base:
  access:
    mode:
      file: "0600"
      dir: "0700"
  paths:
    etc_user: "
      {%- if app_vscode_application['type'] == 'flatpak' -%}
        {{ '/.var/app/com.visualstudio.code/config/Code/User' }}
      {%- elif app_vscode_application['type'] == 'snap' -%}
        {{ '/.config/Code/User' }}
      {%- elif app_vscode_application['type'] == 'distro' -%}
        {{ '/.config/Code/User' }}
      {%- endif -%}
      "
    etc_project: ".vscode"
  templates:
    extensions: "extensions.json.j2"
    settings: "settings.json.j2"
  files:
    user_settings: "settings.json"
    user_extensions: "extensions.json"

app_vscode_profiles:
  distro:
    latest:
      origin: "vscode"
      packages:
        - name: "code"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "com.visualstudio.code"
  snap:
    latest:
      packages:
        - name: "code"
          snap:
            classic: true

# List of plugins that are obsolete and should not be installed
app_vscode_catalog_obsolete:
  - "vscoss.vscode-ansible"
  - "CoenraadS.bracket-pair-colorizer"
  - "CoenraadS.bracket-pair-colorizer-2"
  - "jsonchou.text-compact"
  - "alanwalk.markdown-toc"
  - "zbr.vscode-ansible"
  - "msjsdiag.debugger-for-chrome"
  - "le0zh.vscode-regexp-preivew"

# List of plugins that were broken. Check current status before installing
app_vscode_catalog_broken:
  - "lextudio.restructuredtext"
  - "stephen-riley.regexworkbench"

# List of plugins that are redundant and should not be installed when the alternative is present
app_vscode_catalog_redundant:
  - "hookyqr.beautify"
  - "wholroyd.jinja"
  - "tomaciazek.ansible" # redhat.ansible

# Available plugins for automatic installation
app_vscode_catalog:
  powershell:
    - "ms-vscode.powershell"
    - "ironmansoftware.powershellprotools"
  terraform:
    - "hashicorp.terraform"
    - "ms-azuretools.vscode-azureterraform"
    - "run-at-scale.terraform-doc-snippets"
  dart:
    - "dart-code.dart-code"
    - "dart-code.flutter"
    - "nash.awesome-flutter-snippets"
    - "felixangelov.bloc"
    - "localizely.flutter-intl"
    - "circlecodesolution.ccs-flutter-color"
  css:
    - "raymondcamden.csslint"
    - "syler.sass-indented"
    - "ecmel.vscode-html-css"
    - "zignd.html-css-class-completion"
    - "pranaygp.vscode-css-peek"
  html:
    - "ritwickdey.liveserver"
    - "formulahendry.auto-rename-tag"
    - "abusaidm.html-snippets"
    - "formulahendry.auto-close-tag"
    - "sidthesloth.html5-boilerplate"
    - "tht13.html-preview-vscode"
  jscript:
    - "orta.vscode-jest"
    - "octref.vetur"
    - "xabikos.javascriptsnippets"
  markdown:
    - "eliostruyf.vscode-front-matter"
    - "phoihos.markdown-markmap"
    - "thomascsd.vscode-readme-pattern"
    - "yzhang.markdown-all-in-one"
    - "bierner.markdown-emoji"
    - "bierner.markdown-checkbox"
    - "mdickin.markdown-shortcuts"
    - "bierner.markdown-mermaid"
    - "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
    - "darkriszty.markdown-table-prettify"
    - "DavidAnson.vscode-markdownlint"
  java:
    - "redhat.java"
    - "vscjava.vscode-java-debug"
    - "vscjava.vscode-maven"
    - "vscjava.vscode-java-test"
    - "vscjava.vscode-java-dependency"
    - "pivotal.vscode-spring-boot"
    - "vscjava.vscode-spring-initializr"
    - "vscjava.vscode-spring-boot-dashboard"
  awk:
    - "beaglefoot.awk-ide-vscode"
  jinja:
    - "WyattFerguson.jinja2-snippet-kit"
    - "samuelcolvin.jinjahtml"
  yaml:
    - "docsmsft.docs-yaml"
    - "redhat.vscode-yaml"
    - "tuxtina.json2yaml"
  golang:
    - "golang.go"
  ansible:
    - "redhat.ansible"
  django:
    - "batisteo.vscode-django"
    - "bibhasdn.django-html"
    - "bibhasdn.django-snippets"
  angular:
    - "1tontech.angular-material"
    - "nrwl.angular-console"
    - "cyrilletuzi.angular-schematics"
    - "ms-vscode.vscode-typescript-tslint-plugin"
    - "angular.ng-template"
    - "johnpapa.angular2"
  react:
    - "msjsdiag.vscode-react-native"
    - "dsznajder.es7-react-js-snippets"
  nodejs:
    - "christian-kohler.npm-intellisense"
    - "eg2.vscode-npm-script"
    - "leizongmin.node-module-intellisense"
  jupyter:
    - "ms-toolsai.jupyter"
  flask:
    - "cstrap.flask-snippets"
    - "wasteamaccount.webtemplatestudio-dev-nightly"
  python:
    - "tushortz.python-extended-snippets"
    - "ms-python.vscode-pylance"
    - "njpwerner.autodocstring"
    - "arcticicestudio.nord-visual-studio-code"
    - "EliverLara.andromeda"
    - "kuscamara.electron"
    - "liviuschera.noctis"
    - "lkytal.FlatUI"
    - "ms-python.python"
    - "RobbOwen.synthwave-vscode"
    - "searKing.preview-vscode"
    - "teabyii.ayu"
    - "VisualStudioExptTeam.vscodeintellicode"
    - "seanwu.vscode-qt-for-python"
  shell:
    - "timonwong.shellcheck"
    - "foxundermoon.shell-format"
    - "mikestead.dotenv"
    - "remisa.shellman"
  bash:
    - "mads-hartmann.bash-ide-vscode"
    - "shakram02.bash-beautify"
    - "jetmartin.bats"
    - "rogalmic.bash-debug"
  xml:
    - "dotjoshjohnson.xml"
  drawio:
    - "hediet.vscode-drawio"
  spelling:
    - "streetsidesoftware.code-spell-checker"
  regexp:
    - "louiswt.regexp-preview"
  sql:
    - "mtxr.sqltools"
  aws:
    - "amazonwebservices.aws-toolkit-vscode"
    - "kddejong.vscode-cfn-lint"
    - "aws-scripting-guy.cform"
  docker:
    - "ms-azuretools.vscode-docker"
    - "marquesmps.dockerfile-validator"
  azure:
    - "ms-vscode.azurecli"
  kubernetes:
    - "ms-kubernetes-tools.vscode-kubernetes-tools"
  json:
    - zainchen.json
  remote:
    - "ms-vscode-remote.remote-containers"
    - "ms-vscode-remote.remote-ssh"
    - "ms-vscode-remote.remote-wsl"
  tools:
    - "github.vscode-pull-request-github"
    - "codezombiech.gitignore"
    - "techer.open-in-browser"
    - "oderwat.indent-rainbow"
    - "jannisx11.batch-rename-extension"
    - "slevesque.vscode-multiclip"
    - "johnpapa.vscode-peacock"
    - "randomfractalsinc.vscode-data-preview"
    - "patbenatar.advanced-new-file"
    - "alefragnani.bookmarks"
    - "shardulm94.trailing-spaces"
    - "redhat.fabric8-analytics"
    - "esbenp.prettier-vscode"
    - "anseki.vscode-color"
    - "christian-kohler.path-intellisense"
    - "dbaeumer.vscode-eslint"
    - "spmeesseman.vscode-taskexplorer"
    - "wayou.vscode-todo-highlight"
    - "Tyriar.sort-lines"
    - "donjayamanne.githistory"
    - "eamodio.gitlens"
    - "sleistner.vscode-fileutils"
    - "aaron-bond.better-comments"
    - "alefragnani.project-manager"
    - "dakara.transformer"
    - "daylerees.rainglow"
    - "fabiospampinato.vscode-diff"
    - "formulahendry.code-runner"
    - "jevakallio.vscode-hacker-typer"
    - "ms-vscode-remote.remote-ssh"
    - "ms-vscode-remote.remote-ssh-edit"
    - "qcz.text-power-tools"
    - "ryu1kn.partial-diff"
    - "mechatroner.rainbow-csv"
    - "Shan.code-settings-sync"
    - "moshfeu.compare-folders"
    - "RomanPeshkov.vscode-text-tables"
    - "humao.rest-client"
    - "editorconfig.editorconfig"
  themes:
    - "SolarLiner.linux-themes"
    - "ahmadawais.shades-of-purple"
    - "akamud.vscode-theme-onedark"
    - "akamud.vscode-theme-onelight"
    - "AndrsDC.base16-themes"
    - "azemoh.one-monokai"
    - "azemoh.theme-onedark"
    - "bceskavich.theme-dracula-at-night"
    - "DataByne.theme-monokai-hc"
    - "dcasella.monokai-plusplus"
    - "dracula-theme.theme-dracula"
    - "dunstontc.dark-plus-syntax"
    - "gerane.Theme-azure"
    - "gerane.Theme-Blackboard"
    - "gerane.Theme-Brogrammer"
    - "gerane.Theme-Dark-Dracula"
    - "gerane.Theme-Dracula"
    - "gerane.Theme-FlatDark"
    - "gerane.Theme-Laravel"
    - "gerane.Theme-Monokai"
    - "gerane.Theme-monokai-best"
    - "gerane.Theme-Monokai-Contrast"
    - "gerane.Theme-peel"
    - "gerane.Theme-zacks"
    - "gerane.Theme-Zenburn"
    - "Equinusocio.vsc-community-material-theme"
    - "Equinusocio.vsc-material-theme"
    - "felipe-mendes.slack-theme"
    - "fisheva.eva-theme"
    - "GitHub.github-vscode-theme"
    - "jprestidge.theme-material-theme"
    - "karyfoundation.theme-karyfoundation-themes"
    - "mariorodeghiero.vue-theme"
    - "monokai.theme-monokai-pro-vscode"
    - "ms-vscode.Theme-1337"
    - "ms-vscode.Theme-3024Kit"
    - "ms-vscode.Theme-MarkdownKit"
    - "ms-vscode.Theme-MaterialKit"
    - "naumovs.theme-oceanicnext"
    - "rokoroku.vscode-theme-darcula"
    - "sdras.night-owl"
    - "tinkertrain.theme-panda"
    - "tobiasalthoff.atom-material-theme"
    - "uloco.theme-bluloco-light"
    - "wesbos.theme-cobalt2"
    - "whizkydee.material-palenight-theme"
    - "yummygum.city-lights-theme"
    - "yurihs.sublime-vscode-theme"
    - "zhuangtongfa.material-theme"
    - "johnpapa.winteriscoming"
  icons:
    - "davidbabel.vscode-simpler-icons"
    - "miguelsolorio.fluent-icons"
    - "emmanuelbeziat.vscode-great-icons"
    - "PKief.material-icon-theme"
    - "be5invis.vscode-icontheme-nomo-dark"
    - "equinusocio.vsc-material-theme-icons"
    - "file-icons.file-icons"
    - "jamesmaj.easy-icons"
    - "vscode-icons-team.vscode-icons"

app_vscode_alert_ansible_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.application.app_vscode. Do not modify."

# app_vscode___setup_user: ~
app_vscode___setup_item: ~
app_vscode___setup_extension: ~
app_vscode___setup_extensions: []
...
