---
# Define supported platforms
db_postgresql_server_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
db_postgresql_server_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

# Multiplatform packages
db_postgresql_server_profiles_common:
  snap: {}
  flatpak: {}

# Define common paths
db_postgresql_server_base_common:
  access: {}
  templates: {}
  paths: {}
  files: {}
  run: {}
  etc: {}
...
