---
web_mkdocs_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

web_mkdocs_os_family: "
  {%- if
  ( ansible_distribution == 'CentOS' ) or
  ( ansible_distribution == 'OracleLinux' ) or
  ( ansible_distribution == 'Fedora' )
  -%}
  {{ 'RedHat' }}
  {%- elif
  ( ansible_distribution == 'Debian' ) or
  ( ansible_distribution == 'Ubuntu' )
  -%}
  {{ 'Ubuntu' }}
  {%- else -%}
  {{ 'Linux' }}
  {%- endif -%}
  "

web_mkdocs_base:
  access:
    user:
      owner: "mkdocs"
    group:
      owner: "mkdocs"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  paths:
    root: "/opt/mkdocs"
  run:
    mkdocs: "/opt/mkdocs/mkdocs"

web_mkdocs_profiles:
  pip:
    latest:
      supported: true
      packages:
        - name: "mkdocs"
        - name: "Markdown"
        - name: "mdx-truly-sane-lists"
        - name: "mkdocs-autorefs"
        - name: "mkdocs-awesome-pages-plugin"
        - name: "mkdocs-include-markdown-plugin"
        - name: "mkdocs-markmap"
        - name: "mkdocs-material"
        - name: "mkdocs-mermaid2-plugin"
        - name: "mkdocs-minify-plugin"
        - name: "mkdocstrings"
        - name: "Pygments"
        - name: "pymdown-extensions"
      options:
        pip:
          owner: "{{ web_mkdocs_base['access']['user']['owner'] }}"
          group: "{{ web_mkdocs_base['access']['group']['owner'] }}"
          path: "{{ web_mkdocs_base['paths']['root'] }}"
          cli: "mkdocs"
...
