---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare"
      vars:
        sys_fonts:
          resolve_prereq: true
          prepare: true
      ansible.builtin.include_role:
        name: "sys_fonts"
...
