---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  vars:
    test_path: "/tmp"
    test_file: "test_file_00001.sh"
    test_archive: "test_file_00001.sh.tgz"
    test_target: "/tmp/bkp_archive_provision_tgz_test_target"
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Extract content from TGZ archive"
      vars:
        bkp_archive:
          provision: true
        bkp_archive_files:
          - archive:
              path: "{{ test_path }}"
              file: "{{ test_archive }}"
              keep: false
            content:
              path: "{{ test_target }}"
              name: "{{ test_file }}"
              access:
                owner: "root"
                mode:
                  file: "0644"
      ansible.builtin.include_role:
        name: "bkp_archive"
...
