---
- name: "Side Efect"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  vars:
    test_path: "/tmp"
    test_file: "test_file_00001.sh"
    test_archive: "test_file_00001.sh.tgz"
    test_target: "/tmp/bkp_archive_provision_tgz_test_target"
  tasks:

    - name: "Remove test file"
      ansible.builtin.file:
        state: "absent"
        path: "{{ test_path + '/' + test_file }}"

    - name: "Remove test archive"
      ansible.builtin.file:
        state: "absent"
        path: "{{ test_path + '/' + test_archive }}"

    - name: "Remove test target"
      ansible.builtin.file:
        state: "absent"
        path: "{{ test_target }}"
...
