---
galaxy_info:
  role_name: "bkp_rclone_server"
  author: "serdigital64"
  description: "Manage provisioning of RClone as a server"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "rclone"
dependencies: []
...
