---
- name: "Application / Chrome / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_chrome_platforms

- name: "Application / Chrome / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + app_chrome_os_family + '.yml' }}"
  changed_when: false

- name: "Application / Chrome / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_chrome_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_chrome"
    - app_chrome['resolve_prereq']
...
