---
- name: "DevOps / Molecule / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dops_molecule_platforms

- name: "DevOps / Molecule / Initialize / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "required parameters are missing ({{
      dops_molecule_paths | default('dops_molecule_paths') }} / {{
      dops_molecule_owners | default('dops_molecule_owners') }})"
    that:
      - dops_molecule_paths is defined
      - dops_molecule_owners is defined

- name: "DevOps / Molecule / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dops_molecule_os_family + '.yml' }}"

- name: "DevOps / Molecule / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dops_molecule_prerequisite.yml"
  when:
    - dops_molecule['resolve_prereq'] is defined
    - dops_molecule['resolve_prereq']
...
