---
- name: "DevOps / GitHub / CLI / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dops_github_cli_platforms

- name: "DevOps / GitHub / CLI / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dops_github_cli_os_family + '.yml' }}"

- name: "DevOps / GitHub / CLI / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dops_github_cli_prerequisite.yml"
  when:
    - dops_github_cli['resolve_prereq'] is defined
    - dops_github_cli['resolve_prereq']
...
