---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sec_key_ssh"

    - name: "Detect key"
      become: true
      ansible.builtin.stat:
        path: "/home/test/keys/rsa-4096b"
      register: file_stat

    - name: "Check private key was created"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
