---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "db_mariadb_server"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - db_mariadb_server_platforms is defined
          - db_mariadb_server_profiles is defined
          - db_mariadb_server_application is defined
...
