---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision flatpak repository"
      vars:
        sys_repository:
          provision: true
        sys_repository_managers:
          flatpak: true
      ansible.builtin.include_role:
        name: "sys_repository"
...
