---
# Define supported platforms
app_blender_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
app_blender_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

# Multiplatform packages
app_blender_profiles_common:
  snap: {}
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "org.blender.Blender"

# Define common paths
app_blender_base_common:
  access: {}
  templates: {}
  paths: {}
  files: {}
  run: {}
  etc: {}
...
