---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_dconf"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_dconf_profiles[
          sys_dconf_application['type']
        ][
          sys_dconf_application['version']
        ]['packages']
        }}"
...
