---
namespace: "serdigital64"
name: "devops"
version: "1.1.1"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating devops tools provisioning"
license:
  - "GPL-3.0-or-later"
tags:
  - "development"
  - "devops"
dependencies:
  serdigital64.backup: "*"
  serdigital64.system: "*"
  serdigital64.development: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
