---
- name: "Prepare"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Create test user1"
      become: true
      ansible.builtin.user:
        create_home: true
        system: false
        state: "present"
        name: "test1"

    - name: "Create test user2"
      become: true
      ansible.builtin.user:
        create_home: true
        system: false
        state: "present"
        name: "test2"
...
