---
- name: "Hardware / GPU / AMD / Initialize"
  ansible.builtin.include_tasks:
    file: "hw_gpu_amd_initialize.yml"

- name: "Hardware / GPU / AMD / Deploy"
  ansible.builtin.include_tasks:
    file: "hw_gpu_amd_deploy.yml"
  when:
    - "'deploy' in hw_gpu_amd"
    - "hw_gpu_amd['deploy']"

- name: "Hardware / GPU / AMD / Finalize"
  ansible.builtin.include_tasks:
    file: "hw_gpu_amd_finalize.yml"
...
