---
- name: "Application / X_TASK_ROLE_NAME_X / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ app_pinta_application }}"
    sys_package_profiles: "{{ app_pinta_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
