---
- name: "Application / X_TASK_ROLE_NAME_X / Deploy / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ app_pinta_application | default('app_pinta_application') }})"
    quiet: true
    that:
      - app_pinta_application is defined
      - app_pinta_application | length > 0
      - app_pinta_application['name'] is defined
      - app_pinta_application['type'] is defined
      - app_pinta_application['version'] is defined
      - app_pinta_application['installed'] is defined

- name: "Application / X_TASK_ROLE_NAME_X / Deploy / Package"
  ansible.builtin.include_tasks:
    file: "app_pinta_deploy_package.yml"
  when:
    - app_pinta_application is defined
...
