---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create test user"
      vars:
        sys_user:
          setup: true
        sys_user_accounts:
          - name: "testusr9"
            description: "Test User 9"
            home: "/home/myhome"
            shell: "/usr/bin/bash"
            locked: false
            password: "12345678"
            uid: "10234"
            system: false
            options:
              xdg: true
      ansible.builtin.include_role:
        name: "sys_user"
...
