---
- name: "System / GUI / Cinnamon / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sys_gui_cinnamon_platforms

- name: "System / GUI / Cinnamon / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + sys_gui_cinnamon_os_family + '.yml' }}"
  changed_when: false

- name: "System / GUI / Cinnamon / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sys_gui_cinnamon_prerequisite.yml"
  when:
    - "'resolve_prereq' in sys_gui_cinnamon"
    - sys_gui_cinnamon['resolve_prereq']
...
