---
- name: "System / GUI / Cinnamon / Provision / Nemo / Create user configuration"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ sys_gui_cinnamon_base['access']['user']['owner'] }}"
    group: "{{ sys_gui_cinnamon_base['access']['group']['owner'] }}"
    mode: "{{ sys_gui_cinnamon_base['access']['mode']['file'] }}"
    src: "{{ sys_gui_cinnamon_users['nemo'] + '.toml.j2' }}"
    dest: "{{ sys_gui_cinnamon_base['paths']['var'] + '/' + sys_gui_cinnamon_users['nemo'] }}"

- name: "System / GUI / Cinnamon / Provision / Nemo / Deploy user configuration to DConf"
  vars:
    sys_dconf:
      provision: true
    sys_dconf_db_local:
      - source: "{{ sys_gui_cinnamon_base['paths']['var'] + '/' + sys_gui_cinnamon_users['nemo'] }}"
        name: "{{ 'sys_gui_cinnamon-' + sys_gui_cinnamon_users['nemo'] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_dconf"
...
