---
- name: "System / MC / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sys_mc_platforms

- name: "System / MC / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + sys_mc_os_family + '.yml' }}"
  changed_when: false

- name: "System / MC / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sys_mc_prerequisite.yml"
  when:
    - "'resolve_prereq' in sys_mc"
    - sys_mc['resolve_prereq']
...
