---
- name: "System / MC / Setup / Configuration / MC / Create settings folder ({{
    sys_mc___setup_user['home'] + '/' + sys_mc_base['etc']['mc'] }})"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    mode: "{{ sys_mc_base['access']['mode']['dir'] }}"
    owner: "{{ sys_mc___setup_user['name'] }}"
    group: "{{ sys_mc___setup_user['group'] }}"
    path: "{{ sys_mc___setup_user['home'] + '/' + sys_mc_base['etc']['mc'] }}"

- name: "System / MC / Setup / Configuration / MC / Create default ini"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    mode: "{{ sys_mc_base['access']['mode']['file'] }}"
    owner: "{{ sys_mc___setup_user['name'] }}"
    group: "{{ sys_mc___setup_user['group'] }}"
    src: "{{ sys_mc_base['templates']['ini'] }}"
    dest: "{{ sys_mc___setup_user['home'] + '/' + sys_mc_base['etc']['ini'] }}"

- name: "System / MC / Setup / Configuration / MC / Create default panels.ini"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    mode: "{{ sys_mc_base['access']['mode']['file'] }}"
    owner: "{{ sys_mc___setup_user['name'] }}"
    group: "{{ sys_mc___setup_user['group'] }}"
    src: "{{ sys_mc_base['templates']['panels'] }}"
    dest: "{{ sys_mc___setup_user['home'] + '/' + sys_mc_base['etc']['panels'] }}"
...
