---
- name: "Automation / Ansible / Control / Setup / Engine / Create ansible CLI settings
    ({{ auto_ansible_control_base['files']['ansible_cfg'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    dest: "{{ auto_ansible_control_base['files']['ansible_cfg'] }}"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{ auto_ansible_control_base['templates']['ansible_cfg'] }}"

- name: "Automation / Ansible / Control / Setup / Engine / Create ansible CLI debug settings
    ({{ auto_ansible_control_base['files']['ansible_debug_cfg'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    dest: "{{ auto_ansible_control_base['files']['ansible_debug_cfg'] }}"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{ auto_ansible_control_base['templates']['ansible_debug_cfg'] }}"

- name: "Automation / Ansible / Control / Setup / Engine / Create ansible playbooks common options
    ({{ auto_ansible_control_base['files']['ansible_common'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: false
    unsafe_writes: false
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{ auto_ansible_control_base['templates']['ansible_common'] }}"
    dest: "{{ auto_ansible_control_base['files']['ansible_common'] }}"
...
