---
- name: "Automation / Ansible / Control / Prepare / Paths / Create base structure"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['dir'] }}"
    path: "{{ auto_ansible_control___path['value'] }}"
  loop: "{{ lookup( 'ansible.builtin.dict', auto_ansible_control_base['paths'] ) }}"
  loop_control:
    loop_var: "auto_ansible_control___path"
...
