---
- name: "Automation / Ansible / Control / Setup / Loader / Create environment setup script
    ({{ auto_ansible_control_base['files']['ansible_control_env'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    dest: "{{ auto_ansible_control_base['files']['ansible_control_env'] }}"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['exe'] }}"
    src: "{{ auto_ansible_control_base['templates']['ansible_control_env'] }}"
...
