---
- name: "Automation / Ansible / Control / Provision / Key / Host / Register Ansible Managed Node OpenSSH server keys"
  vars:
    sec_key_ssh:
      setup: true
    sec_key_ssh_knownhosts:
      - file: "{{ auto_ansible_control_base['files']['known_hosts'] }}"
        owner: "{{ auto_ansible_control_base['access']['owner'] }}"
        group: "{{ auto_ansible_control_base['access']['group'] }}"
        hash: false
        hosts: "{{ auto_ansible_control_managed }}"
  ansible.builtin.include_role:
    name: "serdigital64.security.sec_key_ssh"
...
