---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Prepare"
      vars:
        db_mysql_client:
          resolve_prereq: true
          prepare: true
      ansible.builtin.include_role:
        name: "db_mysql_client"
...
