---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Control service"
      vars:
        dops_jenkins:
          setup: true
        dops_jenkins_subsystem:
          enabled: true
          status: "started"
      ansible.builtin.include_role:
        name: "dops_jenkins"
...
