---
- name: "Prepare"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create db"
      ansible.builtin.lineinfile:
        backup: false
        create: true
        unsafe_writes: false
        path: "{{ test_source }}"
        state: "present"
        firstmatch: true
        line: "[/]"

    - name: "Prepare"
      vars:
        sys_dconf:
          resolve_prereq: true
          prepare: true
          setup: true
      ansible.builtin.include_role:
        name: "sys_dconf"
...
