---
- name: "System / Fonts / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sys_fonts_platforms

- name: "System / Fonts / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + sys_fonts_os_family + '.yml' }}"

- name: "System / Fonts / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sys_fonts_prerequisite.yml"
  when:
    - "'resolve_prereq' in sys_fonts"
    - sys_fonts['resolve_prereq']
...
