---
- name: "Application / MS Teams / Initialize"
  ansible.builtin.include_tasks:
    file: "app_msteams_initialize.yml"

- name: "Application / MS Teams / Deploy"
  ansible.builtin.include_tasks:
    file: "app_msteams_deploy.yml"
  when:
    - "'deploy' in app_msteams"
    - "app_msteams['deploy']"

- name: "Application / MS Teams / Finalize"
  ansible.builtin.include_tasks:
    file: "app_msteams_finalize.yml"
...
