---
- name: "Application / Darktable / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_darktable_platforms

- name: "Application / Darktable / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + app_darktable_os_family + '.yml' }}"

- name: "Application / Darktable / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_darktable_prerequisite.yml"
  when:
    - app_darktable['resolve_prereq'] is defined
    - app_darktable['resolve_prereq']
...
