---
- name: "Container / Docker / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in cnt_docker_platforms

- name: "Container / Docker / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + cnt_docker_os_family + '.yml' }}"

- name: "Container / Docker / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "cnt_docker_prerequisite.yml"
  when:
    - cnt_docker['resolve_prereq'] is defined
    - cnt_docker['resolve_prereq']
...
