---
- name: "System / User / Setup / Groups"
  ansible.builtin.include_tasks:
    file: "sys_user_setup_group.yml"
  when:
    - sys_user_groups is defined
    - sys_user_groups | length > 0

- name: "System / User / Setup / Users"
  ansible.builtin.include_tasks:
    file: "sys_user_setup_user.yml"
  when:
    - sys_user_accounts is defined
    - sys_user_accounts | length > 0

- name: "System / User / Setup / XDG"
  ansible.builtin.include_tasks:
    file: "sys_user_setup_xdg.yml"
  when:
    - sys_user_accounts is defined
    - sys_user_accounts | length > 0
...
