---
galaxy_info:
  role_name: "sys_shell"
  author: "serdigital64"
  description: "Manage Unix shells provisioning"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "bash"
    - "zsh"
    - "csh"
    - "ksh"
    - "shell"
dependencies: []
...
