---
- name: "Application / Tilix / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in app_tilix_platforms

- name: "Application / Tilix / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + app_tilix_os_family + '.yml' }}"
  changed_when: false

- name: "Application / Tilix / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "app_tilix_prerequisite.yml"
  when:
    - "'resolve_prereq' in app_tilix"
    - app_tilix['resolve_prereq']
...
