---
- name: "Automation / A:Platform64 / Setup / Inventory / Create initial inventory"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['file'] }}"
    src: "{{
      auto_aplatform64_base['templates']['inventories'] + '/' +
      auto_aplatform64___setup_inventory + '.ini.j2'
      }}"
    dest: "{{
      auto_ansible_control_base['paths']['site_inventories'] + '/' +
      auto_aplatform64___setup_inventory + '.ini'
      }}"
  loop: "{{ auto_aplatform64_inventories }}"
  loop_control:
    loop_var: "auto_aplatform64___setup_inventory"
...
