---
- name: "Automation / A:Platform64 / Prepare / Paths / Create inventory GroupVars repositories"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['dir'] }}"
    path: "{{
      auto_ansible_control_base['paths']['site_group_vars'] + '/' +
      auto_aplatform64___prepare_path_inventory
      }}"
  loop: "{{ auto_aplatform64_host_groups }}"
  loop_control:
    loop_var: "auto_aplatform64___prepare_path_inventory"

- name: "Automation / A:Platform64 / Prepare / Paths / Create var GroupVars repositories"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['dir'] }}"
    path: "{{
      auto_ansible_control_base['paths']['site_var_groups'] + '/' +
      auto_aplatform64___prepare_path_var
      }}"
  loop: "{{ auto_aplatform64_host_groups }}"
  loop_control:
    loop_var: "auto_aplatform64___prepare_path_var"

- name: "Automation / A:Platform64 / Prepare / Paths / Create etc GroupVars repositories"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['dir'] }}"
    path: "{{
      auto_ansible_control_base['paths']['site_etc_groups'] + '/' +
      auto_aplatform64___prepare_path_var
      }}"
  loop: "{{ auto_aplatform64_host_groups }}"
  loop_control:
    loop_var: "auto_aplatform64___prepare_path_var"

- name: "Automation / A:Platform64 / Prepare / Paths / Create files GroupVars repositories"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['dir'] }}"
    path: "{{
      auto_ansible_control_base['paths']['site_files_groups'] + '/' +
      auto_aplatform64___prepare_path_var
      }}"
  loop: "{{ auto_aplatform64_host_groups }}"
  loop_control:
    loop_var: "auto_aplatform64___prepare_path_var"

- name: "Automation / A:Platform64 / Prepare / Paths / Create host settings repository"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: true
    state: "directory"
    owner: "{{ auto_ansible_control_base['access']['owner'] }}"
    group: "{{ auto_ansible_control_base['access']['group'] }}"
    mode: "{{ auto_ansible_control_base['access']['mode']['dir'] }}"
    dest: "{{
      auto_ansible_control_base['paths']['site_host_vars'] +
      '/' + auto_aplatform64___prepare_path_host
      }}"
  loop: "{{ auto_ansible_control_managed }}"
  loop_control:
    loop_var: "auto_aplatform64___prepare_path_host"
...
