---
infra_terraform_repository_custom_yum: []
infra_terraform_repository_custom_apt:
  - name: "hashicorp"
    suite: "{{ ansible_facts['lsb']['codename'] }}"
    component: "main"
    url: "https://apt.releases.hashicorp.com"
    pgpkey: "https://rpm.releases.hashicorp.com/gpg"

infra_terraform_repository_catalog_distro: {}
infra_terraform_repository_catalog_yum: {}
infra_terraform_repository_catalog_apt:
  hashicorp: true
...
