---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_shell:
          resolve_prereq: true
          setup: true
        sys_shell_catalog:
          bash: true
        sys_shell_users:
          - user: "test"
            flavour: "bash"
            home: "/home/test"
            paths:
              - "/test1"
              - "/test2"
            include_system: true
            sources:
              - "/test-source.sh"
            variables:
              - name: "TEST1"
                value: "value1"
                export: true
              - name: "TEST2"
                value: "value2"
                export: true
      ansible.builtin.include_role:
        name: "sys_shell"
...
