---
- name: "Verify"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_shell"

    - name: "Detect rc"
      ansible.builtin.stat:
        path: "/home/test/{{ sys_shell_base['files']['bash_rc'] }}"
      register: file_stat

    - name: "Check rc was created"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
