---
dops_git_server_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

dops_git_server_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

dops_git_server_base_common:
  access:
    owner: "root"
    group: "root"
    mode:
      dir: "0755"
      dir_private: "0700"
  paths:
    root: "{{ dops_git_server_paths['root'] }}"
  run:
    git: "/usr/bin/git"
    git_shell: "/usr/bin/git-shell"

dops_git_server_repository_presets:
  user_geco: "GIT Repository owner"
  user_shell: "{{ dops_git_server_base['run']['git_shell'] }}"
  user_home: "/home"

dops_git_server___provision_git: ~
dops_git_server___provision_status: ~
#dops_git_server___provision_key: ~
#dops_git_server___prepare_path: ~
#dops_git_server___provision_repository: ~
...
