---
galaxy_info:
  role_name: "stg_autofs"
  author: "serdigital64"
  description: "Manage the AutoFS service"
  company: "none"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "any"
  galaxy_tags:
    - "autofs"
dependencies: []
...
