---
cloud_ibm_cli_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

cloud_ibm_cli_base:
  paths:
    root: "/opt/ibmcloud"
    bin: "/opt/ibmcloud/bin"
  run:
    ibmcloud: "/opt/ibmcloud/bin/ibmcloud"
  access:
    group: "root"
    owner: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"

cloud_ibm_cli_profiles:
  binary:
    latest:
      packages:
        - file: "IBM_Cloud_CLI_2.0.0_linux_amd64.tgz"
          uncompress: true
      origin: "https://download.clis.cloud.ibm.com/ibm-cloud-cli/2.0.0/binaries"
      paths:
        - target: "{{ cloud_ibm_cli_base['paths']['root'] }}"
          owner: "{{ cloud_ibm_cli_base['access']['owner'] }}"
          group: "{{ cloud_ibm_cli_base['access']['group'] }}"
          mode: "{{ cloud_ibm_cli_base['access']['mode']['dir'] }}"
        - target: "{{ cloud_ibm_cli_base['paths']['bin'] }}"
          owner: "{{ cloud_ibm_cli_base['access']['owner'] }}"
          group: "{{ cloud_ibm_cli_base['access']['group'] }}"
          mode: "{{ cloud_ibm_cli_base['access']['mode']['dir'] }}"
      promotion:
        - target: "{{ cloud_ibm_cli_base['paths']['bin'] }}"
          source: "IBM_Cloud_CLI/ibmcloud"
          owner: "{{ cloud_ibm_cli_base['access']['owner'] }}"
          group: "{{ cloud_ibm_cli_base['access']['group'] }}"
          mode: "{{ cloud_ibm_cli_base['access']['mode']['exe'] }}"
...
