---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "cloud_aws_realm"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - cloud_aws_realm_platforms is defined
          - cloud_aws_realm_profiles is defined
          - cloud_aws_realm_application is defined
...
