---
- name: "Prepare"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  vars:
    test_path: "/tmp"
    test_file: "test_file_00001.sh"
    test_archive: "test_file_00001.sh.xz"
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        bkp_archive:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "bkp_archive"

    - name: "Create test content"
      ansible.builtin.lineinfile:
        create: true
        line: "echo 'this is a test file'"
        mode: "0644"
        path: "{{ test_path + '/' + test_file }}"
        state: "present"

    - name: "Create test archive"
      ansible.builtin.command:
        argv:
          - "xz"
          - "--compress"
          - "--quiet"
          - "--force"
          - "{{ test_path + '/' + test_file }}"
      register: result
      changed_when:
        - result['rc'] == 0

    - name: "Discover archive file"
      ansible.builtin.stat:
        get_checksum: false
        follow: false
        get_mime: false
        get_attributes: false
        path: "{{ test_path + '/' + test_archive }}"
      register: test_archive_stats

    - name: "Verify the archive was created ({{ test_path + '/' + test_archive }})"
      ansible.builtin.assert:
        that:
          - test_archive_stats['stat']['exists']
...
