---
- name: "Infrastructure / Terraform / Control / Projects / Check that the project code was provisioned (project: {{
    infra_terraform___control_project['name'] }})"
  become: true
  register: "infra_terraform___control_main"
  ansible.builtin.stat:
    follow: false
    get_checksum: false
    get_mime: false
    get_attributes: false
    path: "{{
      infra_terraform_base['paths']['states'] + '/' +
      infra_terraform___control_project['name'] + '/main.tf'
      }}"

- name: "Infrastructure / Terraform / Control / Projects / Run terraform init (project: {{
    infra_terraform___control_project['name'] }})"
  become: true
  become_user: "{{ infra_terraform_base['access']['user']['terraform'] }}"
  register: "infra_terraform___control_init"
  vars:
    infra_terraform___control_path: "{{
      infra_terraform_base['paths']['states'] + '/' +
      infra_terraform___control_project['name']
      }}"
  environment:
    TF_CLI_CONFIG_FILE: "{{ infra_terraform_base['files']['terraform_rc'] }}"
    TF_LOG_PATH: "{{ infra_terraform___control_path + '/' + infra_terraform_base['files']['project_log_init'] }}"
    TF_LOG: "{{ infra_terraform_tool_options['debug'] }}"
  ansible.builtin.command:
    chdir: "{{ infra_terraform___control_path }}"
    argv:
      - "{{ infra_terraform_base['run']['terraform'] }}"
      - "init"
      - "-input=false"
      - "-no-color"
  changed_when:
    - false
  failed_when:
    - infra_terraform___control_init['rc'] != 0
  when:
    - infra_terraform___control_main['stat']['exists']

- name: "Infrastructure / Terraform / Control / Projects / Run terraform apply (project: {{
    infra_terraform___control_project['name'] }})"
  become: true
  become_user: "{{ infra_terraform_base['access']['user']['terraform'] }}"
  register: "infra_terraform___control_apply"
  vars:
    infra_terraform___control_path: "{{
      infra_terraform_base['paths']['states'] + '/' +
      infra_terraform___control_project['name']
      }}"
  environment:
    TF_CLI_CONFIG_FILE: "{{ infra_terraform_base['files']['terraform_rc'] }}"
    TF_LOG_PATH: "{{ infra_terraform___control_path + '/' + infra_terraform_base['files']['project_log_apply'] }}"
    TF_LOG: "{{ infra_terraform_tool_options['debug'] }}"
  ansible.builtin.command:
    chdir: "{{ infra_terraform___control_path }}"
    argv:
      - "{{ infra_terraform_base['run']['terraform'] }}"
      - "apply"
      - "-input=false"
      - "-no-color"
      - "-auto-approve"
  changed_when:
    - infra_terraform___control_apply['rc'] == 0
  failed_when:
    - infra_terraform___control_apply['rc'] != 0
  when:
    - infra_terraform___control_main['stat']['exists']
...
