---
app_zoom_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_zoom_profiles:
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "us.zoom.Zoom"
  snap:
    latest:
      packages:
        - name: "zoom-client"
...
