---
- name: "System / DConf / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sys_dconf_platforms

- name: "System / DConf / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + sys_dconf_os_family + '.yml' }}"

- name: "System / DConf / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sys_dconf_prerequisite.yml"
  when:
    - sys_dconf['resolve_prereq'] is defined
    - sys_dconf['resolve_prereq']
...
