---
- name: "System / Shell / Setup / Profile / User"
  include_tasks:
    file: "{{ 'sys_shell_setup_profile' + '-' + sys_shell___setup_user['flavour'] + '.yml' }}"
  loop: "{{ sys_shell_users }}"
  loop_control:
    loop_var: "sys_shell___setup_user"
  when:
    - "'user' in sys_shell___setup_user"
    - sys_shell___setup_user['user'] | length > 0
    - "'flavour' in sys_shell___setup_user"
    - sys_shell___setup_user['flavour'] | length > 0
    - sys_shell___setup_user['flavour'] in sys_shell_flavour
    - sys_shell___setup_user['flavour'] == "zsh" or sys_shell___setup_user['flavour'] == "bash"
...
