---
- name: "System / Shell / Setup / Profile / Options (user: {{
    sys_shell___setup_profile['user'] }})"
  ansible.builtin.include_tasks:
    file: "sys_shell_setup_profile_options.yml"

- name: "System / Shell / Setup / Profile / ZSH / Deploy Oh-My-ZSH (user: {{
    sys_shell___setup_profile['user'] }})"
  become: true
  #become_user: "{{ sys_shell___setup_profile['user'] }}"
  ansible.builtin.command:
    creates: "{{
      sys_shell___setup_profile['home'] + '/' +
      sys_shell_base['paths']['ohmyzsh_usr']
      }}"
    argv:
      - "/bin/su"
      - "-l"
      - "-c"
      - "{{ sys_shell_base['run']['ohmysh_install'] }} --unattended"
      - "{{ sys_shell___setup_profile['user'] }}"

- name: "System / Shell / Setup / Profile / ZSH / Create Custom Repository ({{
    sys_shell___setup_profile['home'] + '/' + sys_shell_base['paths']['p10k_themes_usr'] }})"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    mode: "{{ sys_shell___setup_profile['access']['mode']['dir'] }}"
    group: "{{ sys_shell___setup_profile['access']['group'] }}"
    owner: "{{ sys_shell___setup_profile['access']['owner'] }}"
    path: "{{ sys_shell___setup_profile['home'] + '/' + sys_shell_base['paths']['p10k_themes_usr'] }}"

- name: "System / Shell / Setup / Profile / ZSH / Deploy PowerLevel10K Theme ({{
    sys_shell___setup_profile['home'] + '/' + sys_shell_base['paths']['p10k_themes_usr'] }})"
  become: true
  ansible.builtin.copy:
    remote_src: true
    backup: false
    follow: false
    force: false
    mode: "{{ sys_shell___setup_profile['access']['mode']['dir'] }}"
    group: "{{ sys_shell___setup_profile['access']['group'] }}"
    owner: "{{ sys_shell___setup_profile['access']['owner'] }}"
    src: "{{ sys_shell_base['paths']['p10k'] }}"
    dest: "{{ sys_shell___setup_profile['home'] + '/' + sys_shell_base['paths']['p10k_themes_usr'] }}"

- name: "System / Shell / Setup / Profile / ZSH / Deploy PowerLevel10K Customized ({{
    sys_shell___setup_profile['home'] + '/' + sys_shell_base['files']['p10k_zsh'] }})"
  become: true
  ansible.builtin.copy:
    backup: false
    follow: false
    force: false
    mode: "{{ sys_shell___setup_profile['access']['mode']['file'] }}"
    group: "{{ sys_shell___setup_profile['access']['group'] }}"
    owner: "{{ sys_shell___setup_profile['access']['owner'] }}"
    src: "{{
      sys_shell_base['paths']['custom_p10k_themes'] + '/' +
      sys_shell___setup_profile['theme']
      }}"
    dest: "{{
      sys_shell___setup_profile['home'] + '/' +
      sys_shell_base['files']['p10k_zsh']
      }}"

- name: "System / Shell / Setup / Profile / ZSH / Configure .zshrc ({{
    sys_shell___setup_profile['home'] + '/' + sys_shell_base['files']['zshrc'] }})"
  become: true
  ansible.builtin.template:
    backup: true
    follow: false
    force: true
    unsafe_writes: false
    mode: "{{ sys_shell___setup_profile['access']['mode']['file'] }}"
    group: "{{ sys_shell___setup_profile['access']['group'] }}"
    owner: "{{ sys_shell___setup_profile['access']['owner'] }}"
    src: "{{ sys_shell_base['templates']['zshrc'] }}"
    dest: "{{ sys_shell___setup_profile['home'] + '/' + sys_shell_base['files']['zshrc'] }}"
...
