---
- name: "System / Shell / Setup / Profile / Options (user: {{
    sys_shell___setup_profile['user'] }})"
  ansible.builtin.include_tasks:
    file: "sys_shell_setup_profile_options.yml"

- name: "System / Shell / Setup / Profile / Bash / Configure .bash_profile ({{
    sys_shell___setup_profile['home'] + '/' + sys_shell_base['files']['bash_profile'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    mode: "{{ sys_shell___setup_profile['access']['mode']['file'] }}"
    group: "{{ sys_shell___setup_profile['access']['group'] }}"
    owner: "{{ sys_shell___setup_profile['access']['owner'] }}"
    src: "{{ sys_shell_base['templates']['bash_profile'] }}"
    dest: "{{ sys_shell___setup_profile['home'] + '/' + sys_shell_base['files']['bash_profile'] }}"

- name: "System / Shell / Setup / Profile / Bash / Configure .bashrc ({{
    sys_shell___setup_profile['home'] + '/' + sys_shell_base['files']['bash_rc'] }})"
  become: true
  ansible.builtin.template:
    backup: true
    follow: false
    force: true
    unsafe_writes: false
    mode: "{{ sys_shell___setup_profile['access']['mode']['file'] }}"
    group: "{{ sys_shell___setup_profile['access']['group'] }}"
    owner: "{{ sys_shell___setup_profile['access']['owner'] }}"
    src: "{{ sys_shell_base['templates']['bash_rc'] }}"
    dest: "{{ sys_shell___setup_profile['home'] + '/' + sys_shell_base['files']['bash_rc'] }}"
...
