---
- name: "System / Shell / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sys_shell_platforms

- name: "System / Shell / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sys_shell_prerequisite.yml"
  when:
    - "'resolve_prereq' in sys_shell"
    - sys_shell['resolve_prereq']
...
