---
- name: "System / Subsystem / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in sys_subsystem_platforms

- name: "System / Subsystem / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + ansible_distribution + ansible_distribution_major_version + '.yml' }}"

- name: "System / Subsystem / Setup / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "sys_subsystem_prerequisite.yml"
  when:
    - "'resolve_prereq' in sys_subsystem"
    - sys_subsystem['resolve_prereq']
...
