---
- name: "Web / NGINX / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in web_nginx_platforms

- name: "Web / NGINX / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + web_nginx_os_family + '.yml' }}"

- name: "Web / NGINX / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "web_nginx_prerequisite.yml"
  when:
    - web_nginx['resolve_prereq'] is defined
    - web_nginx['resolve_prereq']
...
