---
# Define supported platforms
dops_molecule_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
dops_molecule_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

# Multiplatform packages
dops_molecule_profiles_common:
  snap: {}
  flatpak: {}
  pip:
    latest:
      supported: true
      packages:
        - name: "molecule"
      options:
        pip:
          owner: "{{ dops_molecule_owners['app']['name'] }}"
          group: "{{ dops_molecule_owners['app']['group'] }}"
          path: "{{ dops_molecule_paths['root'] }}"
          cli: "{{ dops_molecule_application['name'] }}"

# Define common paths
dops_molecule_base_common:
  access:
    user:
      owner: "root"
      app: "{{ dops_molecule_owners['app']['name'] }}"
    group:
      owner: "root"
      app: "{{ dops_molecule_owners['app']['group'] }}"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates: {}
  files: {}
  etc: {}
  paths:
    root: "{{ dops_molecule_paths['root'] }}"
  run:
    cli: "{{ dops_molecule_paths['root'] + '/' + dops_molecule_application['name'] }}"
...
