---
- name: "Backup / RClone / Server / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in bkp_rclone_server_platforms

- name: "Backup / RClone / Server / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "bkp_rclone_server_prerequisite.yml"
  when:
    - "'resolve_prereq' in bkp_rclone_server"
    - bkp_rclone_server['resolve_prereq']
...
