---
- name: "Backup / RClone / Server / Prerequisite / Prepare package managers"
  vars:
    sys_repository:
      prepare: true
      deploy: true
      setup: true
      provision: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_repository"

- name: "Backup / RClone / Server / Prerequisite / Prepare package installer"
  vars:
    sys_package:
      prepare: true
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
