---
dops_git_client_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

dops_git_client_os_family: "
  {%- if
  ( ansible_distribution == 'CentOS' ) or
  ( ansible_distribution == 'OracleLinux' ) or
  ( ansible_distribution == 'Fedora' )
  -%}
  {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
  {{ 'Ubuntu' }}
  {%- else -%}
  {{ 'Linux' }}
  {%- endif -%}
  "

dops_git_client_base:
  access:
    mode:
      dir: "0700"
      file: "0600"
  templates:
    usr_config: "usr_config.ini.j2"
    prj_config: "prj_config.ini.j2"
    gitignore: "gitignore.ini.j2"
  files:
    project_git_head: ".git/HEAD"
  etc:
    usr_gitconfig: ".gitconfig"
    project_gitignore: ".gitignore"
    project_git_config: ".git/config"
  paths:
    project_git: ".git"
  run:
    git: "/usr/bin/git"

dops_git_client_defaults:
  branch: "main"

dops_git_client___provision_ignore: ~
dops_git_client___provision_git: ~
dops_git_client___provision_status: ~

#dops_git_client___provision_repo
#dops_git_client___setup_user
...
