---
- name: "DevOps / BatsCore / Prepare / Paths / Create"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ dops_batscore___prepare_path }}"
    owner: "{{ dops_batscore_base['access']['owner'] }}"
    group: "{{ dops_batscore_base['access']['group'] }}"
    mode: "{{ dops_batscore_base['access']['mode']['dir'] }}"
  loop:
    - "{{ dops_batscore_base['paths']['root'] }}"
    - "{{ dops_batscore_base['paths']['bin'] }}"
    - "{{ dops_batscore_base['paths']['lib'] }}"
    - "{{ dops_batscore_base['paths']['libexec'] }}"
    - "{{ dops_batscore_base['paths']['plugins'] }}"
    - "{{ dops_batscore_base['paths']['assert'] }}"
    - "{{ dops_batscore_base['paths']['file'] }}"
    - "{{ dops_batscore_base['paths']['support'] }}"
  loop_control:
    loop_var: "dops_batscore___prepare_path"
...
