---
- name: "DevOps / BatsCore / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in dops_batscore_platforms

- name: "DevOps / BatsCore / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + dops_batscore_os_family + '.yml' }}"

- name: "DevOps / BatsCore / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "dops_batscore_prerequisite.yml"
  when:
    - "'resolve_prereq' in dops_batscore"
    - dops_batscore['resolve_prereq']
...
