---
- name: "DevOps / BatsCore / Initialize"
  ansible.builtin.include_tasks:
    file: "dops_batscore_initialize.yml"

- name: "DevOps / BatsCore / Prepare"
  ansible.builtin.include_tasks:
    file: "dops_batscore_prepare.yml"
  when:
    - "'prepare' in dops_batscore"
    - "dops_batscore['prepare']"

- name: "DevOps / BatsCore / Deploy"
  ansible.builtin.include_tasks:
    file: "dops_batscore_deploy.yml"
  when:
    - "'deploy' in dops_batscore"
    - "dops_batscore['deploy']"

- name: "DevOps / BatsCore / Finalize"
  ansible.builtin.include_tasks:
    file: "dops_batscore_finalize.yml"
...
