---
app_drawio_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

app_drawio_profiles:
  snap:
    latest:
      packages:
        - name: "drawio"
  flatpak:
    latest:
      origin: "flathub"
      packages:
        - name: "com.jgraph.drawio.desktop"
...
