---
dependency:
  name: "galaxy"
  options:
    ignore-errors: true
    role-file: "meta/requirements-dev.yml"
    requirements-file: "meta/requirements-dev.yml"
    collections-path: ${APLATFORM64_CACHE_ANSIBLE}
driver:
  name: "podman"
lint: |
  set -e
  yamllint .
  ansible-lint -c ${APLATFORM64_ANSIBLE_LINT} --exclude molecule/
platforms:
  - name: "centos8"
    image: "ghcr.io/serdigital64/centos-8-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "centos"
      - "centos-systemd"
      - "redhat"
      - "redhat-systemd"
      - "rhel"
      - "rhel-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "oraclelinux8"
    image: "ghcr.io/serdigital64/oraclelinux-8-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "oel"
      - "oel-systemd"
      - "redhat"
      - "redhat-systemd"
      - "rhel"
      - "rhel-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "fedora33"
    image: "ghcr.io/serdigital64/fedora-33-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "fedora"
      - "fedora-systemd"
      - "redhat"
      - "redhat-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "fedora35"
    image: "ghcr.io/serdigital64/fedora-35-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "fedora"
      - "fedora-systemd"
      - "redhat"
      - "redhat-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "debian10"
    image: "ghcr.io/serdigital64/debian-10-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "debian"
      - "debian-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "debian11"
    image: "ghcr.io/serdigital64/debian-11-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "debian"
      - "debian-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "ubuntu20"
    image: "ghcr.io/serdigital64/ubuntu-20.4-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "ubuntu"
      - "ubuntu-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
  - name: "ubuntu21"
    image: "ghcr.io/serdigital64/ubuntu-21.4-ansible-node:0.1.0"
    pre_build_image: true
    groups:
      - "ubuntu"
      - "ubuntu-systemd"
      - "linux"
      - "linux-systemd"
    tmpfs:
      - "/run"
      - "/tmp"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    capabilities:
      - "SYS_ADMIN"
    command: "/lib/systemd/systemd"
provisioner:
  name: "ansible"
verifier:
  name: "ansible"
...
