---
- name: "System / Repository / Prepare / Distro / Update repository cache (distro: {{ sys_repository_os_family }})"
  become: true
  no_log: true
  ansible.builtin.command:
    argv:
      - "{{ sys_repository_base['run']['dnf'] }}"
      - "--quiet"
      - "makecache"
  changed_when: false
...
