---
- name: "System / Repository / Provision / Check required parameters"
  ansible.builtin.assert:
    fail_msg: "required parameters are missing ({{
      sys_repository_managers | default('sys_repository_managers') }})"
    quiet: true
    that:
      - sys_repository_managers is defined
      - sys_repository_managers | length > 0

- name: "System / Repository / Provision / Identify repository sources"
  ansible.builtin.set_fact:
    sys_repository___provision_sources:
      distro: "{{ sys_repository_sources['distro'] + sys_repository_custom_distro | default([]) }}"
      flatpak: "{{ sys_repository_sources['flatpak'] + sys_repository_custom_flatpak | default([]) }}"
      yum: "{{ sys_repository_sources['yum'] + sys_repository_custom_yum | default([]) }}"
      apt: "{{ sys_repository_sources['apt'] + sys_repository_custom_apt | default([]) }}"

- name: "System / Repository / Provision / Distro"
  include_tasks:
    file: "sys_repository_provision_distro.yml"
  loop: "{{ sys_repository___provision_sources['distro'] }}"
  loop_control:
    loop_var: "sys_repository___provision_repo"
  when:
    - sys_repository___provision_sources['distro'] | length > 0
    - sys_repository___provision_repo['name'] is defined
    - sys_repository_catalog_distro[sys_repository___provision_repo['name']] is defined

- name: "System / Repository / Provision / FlatPak"
  include_tasks:
    file: "sys_repository_provision_flatpak.yml"
  loop: "{{ sys_repository___provision_sources['flatpak'] }}"
  loop_control:
    loop_var: "sys_repository___provision_repo"
  when:
    - "'flatpak' in sys_repository_managers"
    - sys_repository_managers['flatpak']
    - sys_repository___provision_sources['flatpak'] | length > 0
    - sys_repository___provision_repo['name'] is defined
    - sys_repository_catalog_flatpak[sys_repository___provision_repo['name']] is defined

- name: "System / Repository / Provision / YUM"
  include_tasks:
    file: "sys_repository_provision_yum.yml"
  loop: "{{ sys_repository___provision_sources['yum'] }}"
  loop_control:
    loop_var: "sys_repository___provision_repo"
  when:
    - sys_repository_os_family == "RedHat"
    - sys_repository___provision_sources['yum'] | length > 0
    - sys_repository___provision_repo['name'] is defined
    - sys_repository_catalog_yum[sys_repository___provision_repo['name']] is defined

- name: "System / Repository / Provision / APT"
  include_tasks:
    file: "sys_repository_provision_apt.yml"
  loop: "{{ sys_repository___provision_sources['apt'] }}"
  loop_control:
    loop_var: "sys_repository___provision_repo"
  when:
    - sys_repository_os_family == "Ubuntu"
    - sys_repository___provision_sources['apt'] | length > 0
    - sys_repository___provision_repo['name'] is defined
    - sys_repository_catalog_apt[sys_repository___provision_repo['name']] is defined
...
