---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision"
      vars:
        stg_repository:
          provision: true
        stg_repositories_resources: "{{ test_stg_repositories_resources }}"
      ansible.builtin.include_role:
        name: "stg_repository"
...
