---
- name: "Prepare"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Create source test user"
      become: true
      ansible.builtin.user:
        create_home: true
        system: false
        state: "present"
        name: "test"

    - name: "Create target test user"
      become: true
      ansible.builtin.user:
        create_home: true
        system: false
        state: "present"
        name: "test2"

    - name: "Create key path"
      become: true
      ansible.builtin.file:
        state: "directory"
        mode: "0700"
        path: "/home/test/keys"

    - name: "Install openssh client"
      vars:
        sec_openssh_client:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "serdigital64.security.sec_openssh_client"

    - name: "Create RSA key pair"
      vars:
        sec_key_ssh:
          setup: true
        sec_key_ssh_pairs:
          - file: "rsa-4096b"
            path: "/home/test/keys"
            owner: "test"
            group: "test"
            type: "rsa"
            size: "4096"
      ansible.builtin.include_role:
        name: "sec_key_ssh"
...
