name: "Test / Bash / TestManSH"

on:
  push:
    branches:
      - "develop"

jobs:
  test_batscore_alpine_3:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Download testmansh"
        run: "curl -O https://raw.githubusercontent.com/serdigital64/testmansh/main/testmansh"

      - name: "Prepare build environment"
        run: "./bin/devap-lib"

      - name: "Build app"
        run: "./bin/devap-build -i"

      - name: "Run tests"
        shell: 'script -q -e -c "bash {0}"'
        run: "bash testmansh -b -o -e alpine-3-bash-test:latest"
