---
- name: "Converge"
  hosts: "{{ lookup('env', 'APLATFORM64_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_package:
          provision: true
        sys_package_application:
          name: "DOSBox"
          type: "flatpak"
          version: "latest"
          installed: true
        sys_package_profiles:
          flatpak:
            latest:
              origin: "flathub"
              packages:
                - name: "com.dosbox.DOSBox"
      ansible.builtin.include_role:
        name: "sys_package"
...
