---
cloud_google_cli_base:
  run:
    gcloud: "/usr/bin/gcloud"

cloud_google_cli_profiles:
  distro:
    latest:
      packages:
        - name: "google-cloud-sdk"

cloud_google_cli_repository_custom_yum:
  - name: "google_cloud_sdk"
    description: "Google Cloud SDK"
    url: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64"
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
cloud_google_cli_repository_custom_apt: []

cloud_google_cli_repository_catalog_distro: {}
cloud_google_cli_repository_catalog_yum:
  google_cloud_sdk: true
cloud_google_cli_repository_catalog_apt: {}
...
